[package]
name = "dblzserv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
tokio = "1.21.2"
tonic = "0.8.2"
prost = "0.11.0"
anyhow = { version = "1.0.66", features = ["backtrace"] }
rand = "0.8.5"
mongodb = "2.3.1"
bson = "2.4.0"
dashmap = "5.4.0"

[build-dependencies]
tonic-build = "0.8.2"
